USE [projects]
GO

/****** Object:  Table [dbo].[PROJECT]    Script Date: 09/06/2023 18:52:48 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[PROJECT_SPECIAL](
	[PROJNO] [int] IDENTITY(1,1) NOT NULL,
	[PROJNAME] [varchar](50) NOT NULL,
	[START_DATE][date],
 CONSTRAINT [PK_PROJECT_SPECIAL] PRIMARY KEY CLUSTERED 
(
	[PROJNO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


CREATE TABLE [dbo].[PROJECT](
	[PROJNO] [int] IDENTITY(1,1) NOT NULL,
	[PROJNAME] [varchar](50) NOT NULL,
	[START_DATE][date],
 CONSTRAINT [PK_PROJECT] PRIMARY KEY CLUSTERED 
(
	[PROJNO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

